env:
  browser: true
  commonjs: true
  es6: true
extends:
  - airbnb-base
  - plugin:jest/style
  - plugin:jest/recommended
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
rules:
  "jest/consistent-test-it": error
  comma-dangle: off
plugins:
  - jest
